library:
  source-dirs: src
tests:
  CompiladorLambda-test:
    source-dirs: test
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - random
    - hspec
    - QuickCheck
    - CompiladorLambda
    - MissingH
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- hspec
- base >= 4.7 && < 5
- parsec == 3.1.13.0
- QuickCheck == 2.12.6.1
name: CompiladorLambda
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/CompiladorLambda
license: BSD3
executables:
  CompiladorLambda-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CompiladorLambda
description: Please see the README on GitHub at <https://github.com/githubuser/CompiladorLambda#readme>
