library:
  source-dirs: src
  exposed-modules:
      - Lambda
      - Lambda.DefaultBindings
      - Lambda.Operations.Logic
      - Lambda.Operations.Arithmetics.Integers
      - Lambda.DataTypes.Lists
      - Lambda.DataTypes.Tuples
tests:
   Lambda-test:
    source-dirs: test
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MissingH
    - hspec
    - QuickCheck
    -  Lambda
copyright: 2019 Juan Toca Mateo
maintainer: elan17.programacion@gmail.com
dependencies:
- hashable
- random
- hspec
- base >= 4.7 && < 5
- parsec
- QuickCheck
- unordered-containers
name:  Lambda
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Juan Toca Mateo
github: elan17/LambdaCompiler
license: BSD3
executables:
   Lambda-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    -  Lambda
description: Please see the README on GitHub at https://github.com/elan17/LambdaCompiler
