library:
  source-dirs: src
  exposed-modules: CompiladorLambda
tests:
  CompiladorLambda-test:
    source-dirs: test
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MissingH
    - random
    - hspec
    - QuickCheck
    - CompiladorLambda
copyright: 2019 Juan Toca Mateo
maintainer: elan17.programacion@gmail.com
dependencies:
- hspec
- base >= 4.7 && < 5
- parsec == 3.1.13.0
- QuickCheck == 2.12.6.1
name: CompiladorLambda
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Juan Toca Mateo
github: elan17/LambdaCompiler
license: BSD3
executables:
  CompiladorLambda-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CompiladorLambda
description: Please see the README on GitHub at https://github.com/elan17/LambdaCompiler
